import { EngineCta, EngineHeader, ObjectCard, SectionIntro } from '../../components/engine/EngineUI'

const layers = [
  { title: 'Desk / Capital Generation Layer', body: 'Active trading and desk operations generate the capital that enters the loop.' },
  { title: 'Tokenization Engine', body: 'Intake, verification, and minting turn real-world assets into Asset NFTs.' },
  { title: 'Collateral Engine', body: 'Tokenized assets are posted as collateral to unlock deployable liquidity.' },
  { title: 'Vertical Vaults', body: 'Policy-specific pools hold and manage assets by vertical: reserve, real estate, watches, and more.' },
  { title: 'Markets', body: 'Spot, collateral, vault, prediction, and basket surfaces trade and route asset exposure.' },
  { title: 'Basket Layer', body: 'Indexed positions aggregate exposure across verticals into a single tradable unit.' }
]

export default function ArchitecturePage() {
  return (
    <main className="engine-shell relative overflow-hidden text-[var(--text-1)]">
      <section className="relative z-10 mx-auto max-w-6xl px-6 py-16 sm:px-8 lg:px-10">
        <EngineHeader
          kicker="Kurogami / Docs"
          title="System Architecture"
          subtitle="Trading generates capital. Kurogami structures, protects, and scales it."
        />

        <section className="mt-12 pb-8" aria-labelledby="layers">
          <SectionIntro kicker="System Layers" title="How the layers connect" />
          <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {layers.map((layer) => <ObjectCard key={layer.title} title={layer.title} body={layer.body} />)}
          </div>

          <article className="engine-panel mt-6 p-6 sm:p-8">
            <p className="text-base leading-8 text-white/75 sm:text-lg">
              Capital generated by the desk layer is hardened and routed into the Tokenization Engine, where real-world assets become Asset NFTs. Those units can be posted into the Collateral Engine for liquidity, held in Vertical Vaults, or surfaced through Markets and the Basket Layer for broader portfolio exposure.
            </p>
          </article>

          <div className="mt-8">
            <EngineCta label="View Verticals" href="/verticals" secondaryLabel="Request Access" secondaryHref="#" />
          </div>
        </section>
      </section>
    </main>
  )
}
